### ISSUE TITLE
Vertical structure

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#186]
To help with lowering the barrier of entry between Jupyter and Pyflow, we could adopt a vertical structure where blocks are aligned top to bottom instead of left to right.

A good first step towards this would be having top and bottom sockets

**Comment by MathisFederico** [comment]
> To help with lowering the barrier of entry between Jupyter and Pyflow, we could adopt a vertical structure where blocks are aligned top to bottom instead of left to right.
> 
> A good first step towards this would be having top and bottom sockets

Yup, clearly one of the best ideas, flow should be from up to down as this is how you write lines of code !

**Comment by FabienRoger** [comment]
Sockets are now on the top and bottom of each block (in the middle of each block side, evenly spaced out if there is > 1 socket).
![image](https://user-images.githubusercontent.com/15524303/150499845-54c6a517-4bec-416d-8d49-6b13cb8d47cf.png)

**Comment by FabienRoger** [comment]
The new look of post-conversion ipynb

![image](https://user-images.githubusercontent.com/15524303/150502065-3e2d9791-6ebb-47db-bc29-f54ac1429d3c.png)

I increased the height of each block to be greater than "just the code" so that a few lines of codes can be added without having to move everything down.
This is a quick fix, but I am afraid that we should think of something a bit more clever to allow the user to insert code / blocks in the middle of the graph without having to manually push everything down each time.

**Comment by MathisFederico** [comment]
> This is a quick fix, but I am afraid that we should think of something a bit more clever to allow the user to insert code / blocks in the middle of the graph without having to manually push everything down each time.

Maybe we could use the "block add streamlining" to also push all bellow cells.

Or just add an "insert" option when creating a block like in SpreadSheets tables

**Comment by FabienRoger** [comment]
> This is a quick fix, but I am afraid that we should think of something a bit more clever to allow the user to insert code / blocks in the middle of the graph without having to manually push everything down each time.

See #228 For a way of fixing this
